const user = require("./user")
const productCategory = require("./product_category")
const product = require("./product")
const reseller = require("./reseller")
const productItem = require("./product_item")
const order = require("./order")
const upload = require("./upload")
const productImage = require("./product_image")
const masterImage = require("./master_image")
const controller = {}

controller.user = user
controller.productCategory = productCategory
controller.product = product
controller.reseller = reseller
controller.productItem = productItem
controller.order = order
controller.upload = upload
controller.productImage = productImage
controller.masterImage = masterImage
module.exports=controller